create table userEntities (id int8 generated by default as identity, login varchar(255), name varchar(255), primary key (id));
create table userEntities (id int8 generated by default as identity, login varchar(255), name varchar(255), primary key (id));
